### ISSUE TITLE
Task: Implement OpenAI Embedding models

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/cloai#31]
### Description

See OpenAI's models here https://platform.openai.com/docs/guides/embeddings/embedding-models. These models should be accessible through the CLI, as well as through a Python import. 

### Tasks

- [x] ~~Embedding models must be accessible though the CLI as `cloai embedding [FILENAME] [--model MODEL_NAME]` with output going to STDOUT.~~ EDIT:: Scratch this - since embeddings are only numbers this should be an output file.
- [x] The same model should be accessible through `cloai.openai_api.Embedding` with the async `run()` command. 
- [x] All of these require unit tests.
- [x] change replace_new_lines flag
