### ISSUE TITLE
Task: Add image/audio support for GPT

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/cloai#78]
### Description

GPT-4o can parse audio and images, and output to audio. All of these should be supported.

### Tasks

- [ ] Allow passing an image.
- [ ] Allow passing an audio file.
- [ ] Allow returning audio.
